<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_devices</name>
   <tag></tag>
   <elementGuidId>0ab08ae5-4a4b-45b2-a5fe-b1c8367e2a08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav//a[contains(@href,'devices')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
