<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>panel_body</name>
   <tag></tag>
   <elementGuidId>648e7d5c-7a92-4624-b425-b43fa23077fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//div[contains(@class,'panel-body')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
